
timeline = linspace(1,500,500);

subplot(3,3,1), plot(timeline, left_error_array_x(1, :), 'rx',...
                     timeline, left_error_array_x(2, :), 'rx',...
                     timeline, left_error_array_x(3, :), 'rx',...
                     timeline, left_error_array_x(4, :), 'rx',...
                     timeline, left_error_array_x(5, :), 'rx');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{left}, in mm : x_{axis}')
                 
subplot(3,3,2), plot(timeline, left_error_array_y(1, :), 'rx',...
                     timeline, left_error_array_y(2, :), 'rx',...
                     timeline, left_error_array_y(3, :), 'rx',...
                     timeline, left_error_array_y(4, :), 'rx',...
                     timeline, left_error_array_y(5, :), 'rx');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{left}, in mm : y_{axis}')
                 
subplot(3,3,3), plot(timeline, left_error_array_z(1, :), 'rx',...
                     timeline, left_error_array_z(2, :), 'rx',...
                     timeline, left_error_array_z(3, :), 'rx',...
                     timeline, left_error_array_z(4, :), 'rx',...
                     timeline, left_error_array_z(5, :), 'rx');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{left}, in mm : z_{axis}')
                 
subplot(3,3,4), plot(timeline, right_error_array_x(1, :), 'b+',...
                     timeline, right_error_array_x(2, :), 'b+',...
                     timeline, right_error_array_x(3, :), 'b+',...
                     timeline, right_error_array_x(4, :), 'b+',...
                     timeline, right_error_array_x(5, :), 'b+');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{right}, in mm : x_{axis}')

subplot(3,3,5), plot(timeline, right_error_array_y(1, :), 'b+',...
                     timeline, right_error_array_y(2, :), 'b+',...
                     timeline, right_error_array_y(3, :), 'b+',...
                     timeline, right_error_array_y(4, :), 'b+',...
                     timeline, right_error_array_y(5, :), 'b+');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{right}, in mm : y_{axis}')
                 
subplot(3,3,6), plot(timeline, right_error_array_z(1, :), 'b+',...
                     timeline, right_error_array_z(2, :), 'b+',...
                     timeline, right_error_array_z(3, :), 'b+',...
                     timeline, right_error_array_z(4, :), 'b+',...
                     timeline, right_error_array_z(5, :), 'b+');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{right}, in mm : z_{axis}')
                 
subplot(3,3,7), plot(timeline, nonspread_error_array_x(1, :), 'g*',...
                     timeline, nonspread_error_array_x(2, :), 'g*',...
                     timeline, nonspread_error_array_x(3, :), 'g*',...
                     timeline, nonspread_error_array_x(4, :), 'g*',...
                     timeline, nonspread_error_array_x(5, :), 'g*');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{nonspread}, in mm : x_{axis}')
   
subplot(3,3,8), plot(timeline, nonspread_error_array_y(1, :), 'g*',...
                     timeline, nonspread_error_array_x(2, :), 'g*',...
                     timeline, nonspread_error_array_x(3, :), 'g*',...
                     timeline, nonspread_error_array_x(4, :), 'g*',...
                     timeline, nonspread_error_array_x(5, :), 'g*');
                 grid on
                 axis ([0 500 -60 60])                 
                 xlabel('time')
                 ylabel('e_{nonspread}, in mm : y_{axis}')
                 
subplot(3,3,9), plot(timeline, nonspread_error_array_z(1, :), 'g*',...
                     timeline, nonspread_error_array_z(2, :), 'g*',...
                     timeline, nonspread_error_array_z(3, :), 'g*',...
                     timeline, nonspread_error_array_z(4, :), 'g*',...
                     timeline, nonspread_error_array_z(5, :), 'g*');
                 grid on 
                 axis ([0 500 -60 60])
                 xlabel('time')
                 ylabel('e_{nonspread}, in mm : z_{axis}')                 